version: "2"
plugins:
 eslint:
  channel: "eslint-5"
  enabled: true
  config:
    config: .eslintrc.js
    ignore_warnings: true
exclude_patterns:
- "**/abi.js"
- "**/node_modules/"
- "common/"
- "config/"
- "test/"
- "db/"
- "docs/"
- "python/"
